apiVersion: v1
kind: Pod
metadata:
  name: fastchat-controller
spec:
  containers:
    - name: controller
      image: '192.168.62.116:5000/fastchat'
      command: ["python", "-m", "fastchat.serve.controller"]
      volumeMounts:
        - mountPath: /root/app/fastchat
          name: fastchat-volume
          
     - name: modelworker7b
      image: '192.168.62.116:5000/fastchat'
      command: ["python3", "-m", "fastchat.serve.model_worker","--model-path", "/root/app/models/vicuna-7b", "--gpus", "0,1"]
      resources:
        limits:
          nvidia.com/gpu: 2
      volumeMounts:
        - mountPath: /root/app
          name: fastchat-volume
          
  volumes:
    - name: fastchat-volume
      hostPath:
        path: /home/xuezhi/FastChat/fastchat
